import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins} from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable : "--font-poppins",
  subsets:["latin"],
  weight:["400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Shypbuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased bg-[#1a222c]`}
      >
        <Toaster position="top-center" reverseOrder={false}/>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
